### ISSUE TITLE
Some propertie's values are parsed without 0 at the very begining of string

### ISSUE THREAD

**Issue by lucasow** [deltazero-cz/node-isdoc-pdf#1]
Properties like PartyIdentification->ID or VariableSymbol should be handled as string, not as integer as these properties could starts with 0. In case the value starts with 0 and we are handling it as a integer, 0 char is omitted.

![Capture](https://user-images.githubusercontent.com/37416821/228269768-cba74249-d456-418a-bcb1-768cf272d26d.PNG)

The company identification number in example should be 03622304.

**Comment by deltazero-cz** [comment]
Good point, thanks for letting me know. I'll solve it when I'll have the time, meanwhile feel free to make a pull request :)

**Comment by lucasow** [comment]
Asi nebude vadit, kdyz budu pokracovat v cestine.
Zkousel jsem prijit na to, kde a jak k tomu dochazi, ale zatim neuspesne...

st 29. 3. 2023 v 20:54 odesílatel David Obdržálek [ΔO] <
***@***.***> napsal:

**Comment by deltazero-cz** [comment]
Ahoj, taky jsem to hledal, ale v interface popsané v dep knihovně [node-isdoc](https://github.com/deltazero-cz/node-isdoc/blob/master/lib/interface.ts) je atribut ID typovaný jako string|number.

Zkus ho při generování dokladu (`new Invoice({...})`) poslat jako string, `(number).toString()`, mělo by to tu nulu udržet.

**Comment by lucasow** [comment]
Ahoj,

prave v te node-isdoc knihovne jsem zkousel experimentalne zmenit atribut
pouze na string a stejne se mi vrati integer.
Tu tvoji knihovnu zatim pouzivam k vytezovani isdoc z pdf - tedy
fci extractISDOC - takze zatim nemam sanci vyzkouset to, co navrhujes.

Napadlo me tedy, ze uz v tech fakturach, ktere pouzivam k testovani, jsou
prave ta data spatne zapsana (tzn misto ICO 03622304 tam je 3622304) a moje
snaha vytezit 03622304 je tim padem marna.
Ty mas moznost otestovat vytvoreni faktury napr. s ICO zacinajici 0 a pak
ji zkusit zpetne vytezit?

Lukas

Ahoj, taky jsem to hledal, ale v interface popsané v dep knihovně node-isdoc

**Comment by deltazero-cz** [comment]
Ahoj, máš pravdu. Při tvorbě nového XML to leading zero udrželo, ale při parsování Invoice objektu z XML už to převedlo na číselnou hodnotu. Přenastavil jsem tedy fast-xml-parser tak, aby číselnou hodnotu s leading zero udržel jako string. Díky za podnět.

**Please upgrade to 0.1.2 to keep leading zeros in numeric values**
